name: Build and Deploy Service

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.4.0
      with:
        project_id: ${{ vars.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker image
      run: |
        docker build \
            --build-arg PORT=${{ vars.PORT }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg ENCODER_SERVICE_URL=${{ vars.ENCODER_SERVICE_URL }} \
            -t "gcr.io/$PROJECT_ID/$SERVICE_NAME:latest" .
        docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/geanie-service:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy geanie-service \
          --image gcr.io/${{ vars.GCP_PROJECT_ID }}/geanie-service:latest \
          --platform managed \
          --region ${{ vars.CLOUD_RUN_REGION }}
